name: Booking Movie App build check

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: npm install
      - name: Check IOS build
        run: cd ios && pod install
